name: Build and Release

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
      fail-fast: false
    continue-on-error: true
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get DIST
        run: |
          chmod +x ./print-version.sh
          version=$(./print-version.sh)
          echo "DIST=v$version-$RUNNER_OS" >> $GITHUB_ENV
      - name: Push Git tag
        run: |
          git tag "$DIST"
          git push origin "$DIST"
      - name: Build
        run: |
          ./build.sh "$DIST"
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ env.DIST }}"
          tag_name: "${{ env.DIST }}"
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
